[package]
name = "scope_shadowing"
version = "0.1.0"
authors = ["Alison Venancio <alisonv@eldorado.org.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
